import type { Dataset, Company, Scope } from '../packages/protocol/src/public';
export function fixtureDataset(now = new Date()): Dataset {
  const date = now.toISOString().slice(0, 10),
    until = new Date(now.getTime() + 170 * 86400000).toISOString().slice(0, 10),
    linkUntil = new Date(now.getTime() + 29 * 86400000).toISOString().slice(0, 10);
  const entries = [
    [
      '木序科技有限公司',
      '长沙',
      '430100',
      '软件与信息服务',
      '研发岗位',
      '木序',
      '让工作与生活，各有空间。',
    ],
    [
      '远山食品有限公司',
      '杭州',
      '330100',
      '食品与饮品',
      '总部职能岗位',
      '远山',
      '日常里的认真，来自每一个人。',
    ],
    [
      '青禾设计有限公司',
      '深圳',
      '440300',
      '设计与创意',
      '设计岗位',
      '青禾',
      '好设计，也始于好的工作方式。',
    ],
    [
      '回声软件有限公司',
      '上海',
      '310100',
      '软件与信息服务',
      '产品研发岗位',
      '回声',
      '给专注留出时间。',
    ],
    [
      '木序科技有限公司',
      '苏州',
      '320500',
      '制造与生活用品',
      '办公岗位',
      '木序生活',
      '把用心放进日常。',
    ],
    [
      '晴川服务有限公司',
      '成都',
      '510100',
      '专业服务',
      '客户服务岗位',
      '晴川',
      '有规律的休息，才能走得更远。',
    ],
  ];
  const data: Dataset = {
    schema_version: '1.0',
    demo: true,
    companies: [],
    sources: [],
    brands: [],
    relations: [],
    stores: [],
    products: [],
    links: [],
    rules: [
      {
        rule_version: 'cn-demo-v1',
        jurisdiction: 'CN',
        effective_from: date,
        effective_to: null,
        reviewed_on: date,
        sources: [],
        policy_ttl_days: 180,
        practice_ttl_days: 90,
        warning_days: 30,
        metadata_ttl_hours: 48,
        demo: true,
      },
    ],
    decisions: [],
    mirrors: [],
  };
  entries.forEach(([name, city, cityCode, industry, job, brand, description], i) => {
    const co = `co_demo_${i}`,
      sc = `sc_demo_${i}`,
      src = `src_demo_${i}`,
      br = `br_demo_${i}`,
      st = `st_demo_${i}`,
      ln = `ln_demo_${i}`,
      web = `web_demo_${i}`;
    const scope: Scope = {
      scope_id: sc,
      company_id: co,
      city,
      city_code: cityCode,
      site_label: '示例自营办公场所',
      job_group: job,
      employment_type: 'full_time_employee',
      work_time_regime: 'standard',
      listing_state: 'active',
      record_revision: 1,
      limitations: ['仅为虚构演示，不代表对真实企业的评价。', '未覆盖加盟、外包、生产及其他岗位。'],
      claims: [
        {
          claim_id: `cl_rest_${i}`,
          scope_id: sc,
          dimension: 'rest_schedule',
          value: {
            usual_rest_days_per_week: 2,
            usual_rest_days: i === 5 ? ['tuesday', 'wednesday'] : ['saturday', 'sunday'],
            holiday_adjustments_excluded: true,
          },
          evidence_status: 'source_checked',
          source_ids: [src],
          checked_on: date,
          valid_from: date,
          valid_until: until,
          rule_version: 'cn-demo-v1',
        },
        {
          claim_id: `cl_contract_${i}`,
          scope_id: sc,
          dimension: 'written_contract_policy',
          value: '已公布书面合同制度',
          evidence_status: 'source_checked',
          source_ids: [src],
          checked_on: date,
          valid_from: date,
          valid_until: until,
          rule_version: 'cn-demo-v1',
        },
        {
          claim_id: `cl_pay_${i}`,
          scope_id: sc,
          dimension: 'overtime_payment_practice',
          value: null,
          evidence_status: 'unknown',
          source_ids: [],
          checked_on: null,
          valid_from: null,
          valid_until: null,
          rule_version: 'cn-demo-v1',
        },
      ],
    };
    const company: Company = {
      company_id: co,
      legal_name: name,
      jurisdiction: 'CN',
      public_identifier: `虚构主体 DEMO-${i + 1}`,
      aliases: [brand],
      industry,
      entity_status: 'checked',
      scopes: [scope],
      official_website_link_id: web,
      brand_ids: [br],
    };
    data.companies.push(company);
    data.sources.push({
      source_id: src,
      url: `https://company-${i}.example/policy`,
      title: '示例企业公开工作制度（虚构）',
      publisher: name,
      published_on: date,
      checked_on: date,
      source_family: `family_demo_${i}`,
      kind: 'company',
      supported_claim_ids: [`cl_rest_${i}`, `cl_contract_${i}`],
    });
    data.brands.push({ brand_id: br, name: brand, categories: [industry] });
    data.relations.push({
      relation_id: `rel_demo_${i}`,
      company_id: co,
      brand_id: br,
      relation_type: 'owned',
      source_ids: [src],
      valid_until: until,
    });
    data.stores.push({
      store_id: st,
      brand_id: br,
      platform: '品牌自有网站',
      platform_store_id: `example-store-${i}`,
      seller_company_id: co,
      relation_type: 'owned',
      verification_state: 'approved',
      source_ids: [src],
      valid_until: until,
    });
    for (const [linkId, type, url, store] of [
      [web, 'official_website', `https://company-${i}.example`, null],
      [ln, 'service_page', `https://company-${i}.example/store`, st],
    ] as const)
      data.links.push({
        link_id: linkId,
        type,
        url,
        store_id: store,
        seller_company_id: co,
        linked_scope_ids: [sc],
        relation_source_ids: [src],
        checked_on: date,
        valid_until: linkUntil,
        ad_label: store ? '广告 · 商品/服务推广（本站不收取购买佣金）' : '',
        status: 'active',
      });
    data.products.push({
      product_id: `prod_demo_${i}`,
      brand_id: br,
      category: industry,
      title: brand + ' · 产品与服务',
      store_id: st,
      link_id: ln,
      promotion_status: 'approved',
      description,
    });
  });
  return data;
}
